# Generated by Django 4.2.1 on 2023-06-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Спеціалізація')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('years_of_experience', models.IntegerField(verbose_name='Років досвіду роботи')),
                ('education', models.CharField(max_length=100, verbose_name='Освіта')),
                ('photo', models.ImageField(upload_to='doctor_photos', verbose_name='Фото')),
                ('additional_info', models.TextField(verbose_name='Додаткова інформація про досвід роботи')),
                ('specialization', models.ManyToManyField(to='doctor.specialization', verbose_name='Спеціалізації')),
            ],
        ),
    ]
