# Generated by Django 4.2.1 on 2023-06-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва')),
                ('photo', models.ImageField(upload_to='news_photos', verbose_name='Фото')),
                ('content', models.TextField(verbose_name='Текст')),
                ('publication_date', models.DateField(verbose_name='Дата публікації')),
            ],
        ),
    ]
